---
exclude: |
    (?x)(
        ^tests/nsis3/|
        ^web/external/|
        \.svg
    )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-json
      - id: check-toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.13
    hooks:
      - id: ruff-check
  - repo: https://github.com/crate-ci/typos
    rev: v1.46.2
    hooks:
      - id: typos
