[files]
extend-exclude = [
    ".scrutinizer.yml",
    "external",
    "nsis3",
    "tests/cat_integration_scrutinizer.sql",
    "translation",
]

[default.extend-identifiers]
recognisedOShs20 = "recognisedOShs20"
return_doc_comment_if_not_inferrable = "return_doc_comment_if_not_inferrable"
param_doc_comment_if_not_inferrable = "param_doc_comment_if_not_inferrable"
SELECTs = "SELECTs"
setRADIUSconfig = "setRADIUSconfig"
StrCpy = "StrCpy"
SURFnet = "SURFnet"

[default.extend-words]
BA = "BA"
FO = "FO"
gost = "gost"
interm = "interm"
MODULU = "MODULU"
ois = "ois"
OT = "OT"
passin = "passin"
pendings = "pendings"
PN = "PN"
tou = "tou"
Widgits = "Widgits"
