services:
    msp:
        build: .
        image: msp
        container_name: msp
        network_mode: host
        attach: false
        restart: always
        env_file:
        - "msp.env"
        volumes:
          - ./sp-conf:/opt/SPs
          - sp-logs:/opt/FR/var/log
          - ./certs:/var/tmp/certs
volumes:
   sp-logs:
       name: sp-logs
