#!/bin/bash
# see HOWTO in this directory to learn how to produce the files you need
# all certificates and key files should be in the directory pointed to by MY_PATH

# MY_PATH - Full path to the directory in which the certificates and keys are located
# Beware that this directory must be protected against the WEB download, othewise you keys mey be compromised. 
# The directory must be accessible by the Apache proceess

MY_PATH=""

#
# public key in the SPC format
SPC="xxx.spc"
# maching private key, it cannot be password protected
PRIVKEY="xxx_key.der"
# URL shown to the user requiring more information about your installer
URL=""
# product name
NAME=""

osslsigncode -spc "$MY_PATH/$SPC" -key "$MY_PATH/$PRIVKEY" -n "$NAME" -i "$URL" -in  $1 -out $2
